# Generated by Django 3.2.18 on 2023-05-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaName', models.CharField(max_length=50)),
                ('partName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tel', models.CharField(max_length=30)),
                ('usedTime', models.CharField(max_length=200)),
                ('homePage', models.URLField()),
                ('content', models.TextField()),
                ('provisionSupply', models.CharField(max_length=300)),
                ('petFacility', models.CharField(max_length=300)),
                ('restaurant', models.CharField(max_length=300)),
                ('parkingLog', models.CharField(max_length=300)),
                ('mainFacility', models.CharField(max_length=300)),
                ('usedCost', models.CharField(max_length=300)),
                ('policyCautions', models.CharField(max_length=300)),
                ('emergencyResponse', models.CharField(max_length=300)),
                ('memo', models.TextField()),
                ('bathFlag', models.CharField(max_length=10)),
                ('provisionFlag', models.CharField(max_length=10)),
                ('petFlag', models.CharField(max_length=10)),
                ('petWeight', models.CharField(max_length=10)),
                ('dogBreed', models.CharField(max_length=10)),
                ('emergencyFlag', models.CharField(max_length=10)),
                ('entranceFlag', models.CharField(max_length=10)),
                ('parkingFlag', models.CharField(max_length=10)),
                ('inOutFlag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
