# Generated by Django 3.2.18 on 2023-05-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark_place', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placeimg',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageList', to='places.place'),
        ),
    ]
